# ============================================================
# GRADLE
# ============================================================

# Reutiliza la información de configuración entre ejecuciones
# para reducir el tiempo necesario para iniciar un build.
org.gradle.configuration-cache=true

# Mantiene el proceso de Gradle activo entre ejecuciones,
# evitando tener que iniciarlo nuevamente en cada build.
org.gradle.daemon=true

# Permite ejecutar tareas de proyectos independientes
# en paralelo cuando sea posible.
org.gradle.parallel=true

# Habilita la caché de Gradle para reutilizar resultados
# de tareas que no necesitan ejecutarse nuevamente.
org.gradle.caching=true
