[versions]
jjwt = "0.13.0"
springDotenv = "4.0.0"
springdoc = "2.8.13"

[libraries]
jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt" }
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt" }
spring-dotenv = { module = "me.paulschwarz:spring-dotenv", version.ref = "springDotenv" }
springdoc-openapi = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }