server:
  port: 8080

spring:
  profiles:
    active: dev

  application:
    name: football-market

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  jackson:
    time-zone: America/Argentina/Buenos_Aires

logging:
  level:
    root: INFO
    ar.edu.unq.schoolmanager: DEBUG
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF
    org.hibernate.stat: OFF