server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: false

  jackson:
    time-zone: America/Argentina/Buenos_Aires

logging:
  level:
    root: INFO
    ar.edu.unq.schoolmanager: DEBUG